"""Context Assembly Engine for DevBrain (PAIOS Layer).

Merges User Preferences, Project State, Architecture Decisions (ADRs),
Relevant Knowledge Base Chunks, and Recent Work Summaries into a compact situational briefing card.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from devbrain.adr.manager import ADRManager
from devbrain.core.constants import DIR_INBOX, DIR_PROJECTS, DIR_SYSTEM
from devbrain.core.sqlite_db import BrainSQLiteStorage


@dataclass
class TaskContextCard:
    """Assembled situational awareness context card for AI Agents."""

    task: str
    project: str
    user_preferences: str
    project_summary: str
    tech_stack: list[str]
    active_decisions: list[dict[str, Any]]
    relevant_knowledge: list[dict[str, Any]]
    recent_session_work: list[str]
    generated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_markdown(self) -> str:
        """Render context card as a dense Markdown prompt block for LLMs."""
        adrs_text = ""
        if self.active_decisions:
            for adr in self.active_decisions:
                adrs_text += f"- **[{adr.get('id', 'ADR')}] {adr.get('title', '')}** (Status: `{adr.get('status', 'accepted')}`)\n"
        else:
            adrs_text = "- Belum ada keputusan arsitektur (ADR) aktif yang tercatat.\n"

        kb_text = ""
        if self.relevant_knowledge:
            for item in self.relevant_knowledge:
                kb_text += f"- **{item.get('title', item.get('path', 'Knowledge'))}**: {item.get('snippet', '')[:160]}...\n"
        else:
            kb_text = "- Tidak ada catatan knowledge khusus yang terpicu untuk task ini.\n"

        recent_text = ""
        if self.recent_session_work:
            for item in self.recent_session_work:
                recent_text += f"- {item}\n"
        else:
            recent_text = "- Tidak ada riwayat sesi pengerjaan terbaru.\n"

        stack_str = ", ".join(self.tech_stack) if self.tech_stack else "Standard Stack"

        return f"""# 🧠 SITUATIONAL TASK CONTEXT BRIEFING

## 🎯 Target Task & Project
- **Active Project:** [[{self.project}]]
- **Target Task:** {self.task}
- **Tech Stack:** {stack_str}
- **Briefing Timestamp:** `{self.generated_at}`

---

## 👤 User Preferences & Coding Persona
{self.user_preferences.strip() if self.user_preferences else 'Standard Clean Code, Type Safety, Modular Architecture.'}

---

## 🏗️ Active Architecture Decisions (ADR Constraints)
{adrs_text.strip()}

---

## 📁 Project Architecture & Context
{self.project_summary.strip() if self.project_summary else f'Project context for {self.project}.'}

---

## 📚 Relevant Knowledge Base Chunks
{kb_text.strip()}

---

## 🕒 Recent Session Work History
{recent_text.strip()}

---
*Generated by DevBrain PAIOS Context Assembly Engine.*
"""

    def to_dict(self) -> dict[str, Any]:
        """Convert context card to dictionary representation."""
        return {
            "task": self.task,
            "project": self.project,
            "user_preferences": self.user_preferences,
            "project_summary": self.project_summary,
            "tech_stack": self.tech_stack,
            "active_decisions": self.active_decisions,
            "relevant_knowledge": self.relevant_knowledge,
            "recent_session_work": self.recent_session_work,
            "generated_at": self.generated_at,
        }


class ContextAssemblyEngine:
    """Orchestrates multi-source context assembly for fast AI agent priming."""

    def __init__(self, vault_path: Path, sqlite_storage: Optional[BrainSQLiteStorage] = None):
        self.vault_path = Path(vault_path).resolve()
        self.sqlite = sqlite_storage or BrainSQLiteStorage(self.vault_path)
        self.adr_manager = ADRManager(self.vault_path, self.sqlite)

    def get_user_preferences(self) -> str:
        """Fetch user preferences from 00_System/User_Preferences.md or SQLite memories."""
        pref_file = self.vault_path / DIR_SYSTEM / "User_Preferences.md"
        if pref_file.is_file():
            try:
                with open(pref_file, "r", encoding="utf-8") as f:
                    return f.read().strip()
            except Exception:
                pass

        # Check SQLite global memories
        mems = self.sqlite.get_memories(scope="GLOBAL", status="active")
        if mems:
            lines = [f"- {m['content']}" for m in mems]
            return "### User Preferences (Stored in DevBrain):\n" + "\n".join(lines)

        return "- Language: TypeScript / Python (Strict Mode)\n- Architecture: Modular, Clean Code, DRY\n- Testing: Comprehensive Unit & Integration Tests\n- Documentation: Clear docstrings and updated CHANGELOG.md"

    def get_project_summary(self, project_name: str) -> tuple[str, list[str]]:
        """Extract project summary and detected tech stack from 10_Projects/."""
        proj_dir = self.vault_path / DIR_PROJECTS / project_name
        proj_file = proj_dir / "README.md"
        if not proj_file.is_file():
            proj_file = self.vault_path / DIR_PROJECTS / f"{project_name}.md"

        if not proj_file.is_file():
            return f"Project [[{project_name}]] registered in DevBrain.", []

        try:
            with open(proj_file, "r", encoding="utf-8") as f:
                content = f.read()

            summary = content[:500]
            stack: list[str] = []
            if "python" in content.lower() or "pyproject.toml" in content.lower():
                stack.append("Python")
            if "typescript" in content.lower() or "tsconfig.json" in content.lower():
                stack.append("TypeScript")
            if "react" in content.lower() or "next.js" in content.lower():
                stack.append("Next.js/React")
            if "laravel" in content.lower() or "php" in content.lower():
                stack.append("Laravel/PHP")
            if "fastapi" in content.lower():
                stack.append("FastAPI")
            if "docker" in content.lower():
                stack.append("Docker")

            return summary, stack
        except Exception:
            return f"Project [[{project_name}]]", []

    def get_recent_inbox_work(self, project_name: str, limit: int = 3) -> list[str]:
        """Fetch latest session work notes related to the project."""
        inbox_dir = self.vault_path / DIR_INBOX
        if not inbox_dir.is_dir():
            return []

        recent_files = sorted(
            inbox_dir.rglob("*.md"),
            key=lambda p: p.stat().st_mtime if p.is_file() else 0,
            reverse=True,
        )

        results: list[str] = []
        for file in recent_files:
            if len(results) >= limit:
                break
            try:
                name = file.stem
                if project_name.lower() in file.name.lower() or project_name.lower() in file.read_text(encoding="utf-8")[:300].lower():
                    results.append(f"Recent session: [[{name}]] ({file.parent.name})")
            except Exception:
                continue

        return results

    def build_task_context(
        self,
        task: str,
        project: str,
        relevant_chunks: Optional[list[dict[str, Any]]] = None,
    ) -> TaskContextCard:
        """Assemble all 5 context tiers into a coherent TaskContextCard."""
        user_prefs = self.get_user_preferences()
        proj_summary, stack = self.get_project_summary(project)
        active_adrs = self.adr_manager.list_decisions(project=project, status="accepted")
        recent_work = self.get_recent_inbox_work(project, limit=3)

        return TaskContextCard(
            task=task,
            project=project,
            user_preferences=user_prefs,
            project_summary=proj_summary,
            tech_stack=stack,
            active_decisions=active_adrs,
            relevant_knowledge=relevant_chunks or [],
            recent_session_work=recent_work,
        )
